---
Layout: Default
author_profile: true
toc: true
toc_sticky: true
categories:
    - python_basic
tags: [Python, 기초]
---

# 구문오류와 예외
## 오류의 종류
- 프로그램 실행 전 발생 오류: syntax error(문법 자체가 틀린 경우)
- 프로그램 실행 중 발생 오류: Runtime error 또는 예외(Exeption)  

예외의 예
- Index error
- time error
- value error  

예외처리(Exeption Handling)를 통하여 예측하지 못한 에러를 처리할 수 있다.

<br>

## 예외를 처리하는 방법
1. if 조건식을 통한 필터링

```python
x = input("정수 입력")
if x.isdigit():
    x_num = int(x)
    ...
```
    
2. Try Except 키워드 구문

<br>

## try-except 
try문 안에 실행문을 실행 중 오류가 발생하면 except 예외 처리문이 실행된다.

```python
try:
    실행문
except:
    예외 처리문
```

<br>

```python
list_input_a = ["52", "273", "32", "스파이", "103"]

list_number = []

# try 예외 처리문을 사용하면 for문에 문제가 발생하더라도 중단되지 않고 모두 실행할 수 있다.
for item in list_input_a:
    try:
        float(item)
        list_number.append(item)
    except:
        pass

print("{} 내부에 있는 숫자는".format(list_input_a))
print("{}입니다.".format(list_number))
```

런타임 오류에 대비하기 위해 모든 코드를 try 문으로 감싸줘도 되겠지만,  
오류 발생 지점을 찾고 디버깅 하기 위해서는 구간마다 try문을 분리해서 작성합니다.

<br>

## try-except-else
else 구문은 try에서 오류가 발생하지 않았을 때 실행된다.

```python
try:
    예외 발생 가능성이 있는 코드
except:
    예외가 발생했을 때 실행되는 코드
else:
    예외가 발생되지 않았을 때 실행되는 코드
```

<br>

올바른 입력을 받기 위한 예외 처리문

```python
while True:
    try:
        number_input = int(input("정수입력> "))
    except:
        print("정수를 입력하지 않았습니다.")
    else:
        print("원의 반지름: ", number_input)
        print("원의 둘레: ", 2 * 3.14 * number_input)
        print("원의 넓이: ", 3.14 * number_input * number_input)
```

<br>

## finally 
예외 여부 상관 없이 실행되는 구문입니다.

```python
try:
    예외 발생 가능성이 있는 코드
except:
    예외가 발생했을 때 실행되는 코드
else:
    예외가 발생되지 않았을 때 실행되는 코드
finally:
    무조건 실행할 코드
```

<br>

```python
try:
    file = open("info.txt", "w")
    # 파일 처리 수행
    # ~~~

    file.close()
except:
    print("오류가 발생했습니다.")

print("# 파일이 제대로 닫혔는지 확인하기")
print(f"{file.closed=}")

```

<br>

`try`문에서 `return`으로 조기 반환 되더라도 `finally`의 실행문은 실행된다.  
함수뿐만 아니라 `while`문 등의 반복문에서 `break`를 통해 빠져나오더라도 `finally`문은 실행된다.

```python
def test():
    try:
        return 0
        x = int(input("입력> "))
        print(x)
    except Exception as e:
        print(e)
    else:
        print("오류 없음")
    finally:
        print("오류 발생 여부 상관없이 무조건 실행")

test()
```

<br>
<br>

# 예외 고급
## 특정 예외만 받기
```python
try:
    
except 예외의 종류A:

except 예외의 종류B:

except 예외의 종류C:
```

```python
try:
    file = open("test.txt", "r")
    file.close()

# Exception은 예외 객체이며, except 구문 뒤에 어떤 예외를 받을 것인지 작성할 수 있다.
# as 키워드로 별명을 설정한다.
except Exception as e:
    print("에러발생", e)
```

<br>

특정 에러를 잡고, 예상치 못한 에러들 까지 잡는 방법이다.

```python
try:
    실행문
except ValueError as e:
    print("Value 에러", e)
except IndexError as e:
    print("Index 에러", e)
except Exception as e:
    print("예측하지 못한 에러", e)
```

## raise
`raise`는 예외를 강제로 발생시킬 수 있는 키워드이다.

개발 중 나중에 꼭 구현하도록 넣거나, 사용자가 들어가서는 안되는 코드에 들어갈 때 실행되도록 하여 위험을 막을 수 있다.

```python
if 어떤 경우:
    raise error 객체    # 에러를 발생시키겠다.
```

